DetectPoisonedSamples|CIFAR10|ResNet18|Refool
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/ResNet18/Refool/0.01/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/ResNet18/Refool/0.03/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/ResNet18/Refool/0.05/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/ResNet18/Refool/0.07/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/ResNet18/Refool/0.09/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/ResNet18/Refool/0.1/P_R_F1_dict.data
DetectPoisonedSamples|CIFAR10|ResNet18|BadNets
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/ResNet18/BadNets/0.01/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/ResNet18/BadNets/0.03/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/ResNet18/BadNets/0.05/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/ResNet18/BadNets/0.07/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/ResNet18/BadNets/0.09/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/ResNet18/BadNets/0.1/P_R_F1_dict.data
DetectPoisonedSamples|CIFAR10|ResNet18|WaNet
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/ResNet18/WaNet/0.01/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/ResNet18/WaNet/0.03/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/ResNet18/WaNet/0.05/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/ResNet18/WaNet/0.07/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/ResNet18/WaNet/0.09/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/ResNet18/WaNet/0.1/P_R_F1_dict.data
DetectPoisonedSamples|CIFAR10|VGG19|BadNets
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/VGG19/BadNets/0.01/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/VGG19/BadNets/0.03/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/VGG19/BadNets/0.05/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/VGG19/BadNets/0.07/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/VGG19/BadNets/0.09/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/VGG19/BadNets/0.1/P_R_F1_dict.data
DetectPoisonedSamples|CIFAR10|ResNet18|IAD
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/ResNet18/IAD/0.01/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/ResNet18/IAD/0.03/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/ResNet18/IAD/0.05/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/ResNet18/IAD/0.07/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/ResNet18/IAD/0.09/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/ResNet18/IAD/0.1/P_R_F1_dict.data
DetectPoisonedSamples|CIFAR10|VGG19|Refool
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/VGG19/Refool/0.01/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/VGG19/Refool/0.03/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/VGG19/Refool/0.05/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/VGG19/Refool/0.07/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/VGG19/Refool/0.09/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/VGG19/Refool/0.1/P_R_F1_dict.data
DetectPoisonedSamples|CIFAR10|VGG19|IAD
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/VGG19/IAD/0.01/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/VGG19/IAD/0.03/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/VGG19/IAD/0.05/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/VGG19/IAD/0.07/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/VGG19/IAD/0.09/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/VGG19/IAD/0.1/P_R_F1_dict.data
DetectPoisonedSamples|CIFAR10|VGG19|WaNet
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/VGG19/WaNet/0.01/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/VGG19/WaNet/0.03/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/VGG19/WaNet/0.05/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/VGG19/WaNet/0.07/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/VGG19/WaNet/0.09/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/VGG19/WaNet/0.1/P_R_F1_dict.data
DetectPoisonedSamples|CIFAR10|DenseNet|Refool
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/DenseNet/Refool/0.01/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/DenseNet/Refool/0.03/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/DenseNet/Refool/0.05/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/DenseNet/Refool/0.07/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/DenseNet/Refool/0.09/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/DenseNet/Refool/0.1/P_R_F1_dict.data
DetectPoisonedSamples|CIFAR10|DenseNet|WaNet
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/DenseNet/WaNet/0.01/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/DenseNet/WaNet/0.03/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/DenseNet/WaNet/0.05/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/DenseNet/WaNet/0.07/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/DenseNet/WaNet/0.09/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/DenseNet/WaNet/0.1/P_R_F1_dict.data
DetectPoisonedSamples|CIFAR10|DenseNet|BadNets
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/DenseNet/BadNets/0.01/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/DenseNet/BadNets/0.03/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/DenseNet/BadNets/0.05/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/DenseNet/BadNets/0.07/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/DenseNet/BadNets/0.09/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/DenseNet/BadNets/0.1/P_R_F1_dict.data
DetectPoisonedSamples|CIFAR10|DenseNet|IAD
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/DenseNet/IAD/0.01/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/DenseNet/IAD/0.03/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/DenseNet/IAD/0.05/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/DenseNet/IAD/0.07/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/DenseNet/IAD/0.09/P_R_F1_dict.data
数据保存在:/data/mml/backdoor_detect/experiments/DetectPoisonedSamples/CIFAR10/DenseNet/IAD/0.1/P_R_F1_dict.data
Traceback (most recent call last):
  File "/home/mml/workspace/backdoor_detect/codes/ourMethod/detect_suspicious_classes/analyse.py", line 62, in <module>
    backdoor_data = torch.load(backdoor_data_path, map_location="cpu")
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/data/mml/backdoor_detect/experiments/ATTACK/CIFAR10/VGG19/Refool /backdoor_data.pth'
Traceback (most recent call last):
  File "/home/mml/workspace/backdoor_detect/codes/ourMethod/detect_suspicious_classes/analyse.py", line 70, in <module>
    poisoned_report = get_mutated_models_eval_report(poisonedDataset)
  File "/home/mml/workspace/backdoor_detect/codes/ourMethod/detect_suspicious_classes/analyse.py", line 32, in get_mutated_models_eval_report
    report = em.eval_classification_report()
  File "/home/mml/workspace/backdoor_detect/codes/common/eval_model.py", line 107, in eval_classification_report
    for batch_id, batch in enumerate(testset_loader):
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mml/workspace/backdoor_detect/codes/scripts/dataset_constructor.py", line 180, in __getitem__
    sample,label =self.new_dataset[index]
ValueError: too many values to unpack (expected 2)

Traceback (most recent call last):
  File "/home/mml/workspace/backdoor_detect/codes/ourMethod/detect_suspicious_classes/analyse.py", line 70, in <module>
    poisoned_report = get_mutated_models_eval_report(poisonedDataset)
  File "/home/mml/workspace/backdoor_detect/codes/ourMethod/detect_suspicious_classes/analyse.py", line 32, in get_mutated_models_eval_report
    report = em.eval_classification_report()
  File "/home/mml/workspace/backdoor_detect/codes/common/eval_model.py", line 107, in eval_classification_report
    for batch_id, batch in enumerate(testset_loader):
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mml/workspace/backdoor_detect/codes/scripts/dataset_constructor.py", line 180, in __getitem__
    sample,label =self.new_dataset[index]
ValueError: too many values to unpack (expected 2)

Traceback (most recent call last):
  File "/home/mml/workspace/backdoor_detect/codes/ourMethod/detect_suspicious_classes/analyse.py", line 70, in <module>
    poisoned_report = get_mutated_models_eval_report(poisonedDataset)
  File "/home/mml/workspace/backdoor_detect/codes/ourMethod/detect_suspicious_classes/analyse.py", line 32, in get_mutated_models_eval_report
    report = em.eval_classification_report()
  File "/home/mml/workspace/backdoor_detect/codes/common/eval_model.py", line 107, in eval_classification_report
    for batch_id, batch in enumerate(testset_loader):
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mml/workspace/backdoor_detect/codes/scripts/dataset_constructor.py", line 180, in __getitem__
    sample,label =self.new_dataset[index]
ValueError: too many values to unpack (expected 2)

Traceback (most recent call last):
  File "/home/mml/workspace/backdoor_detect/codes/ourMethod/detect_suspicious_classes/analyse.py", line 70, in <module>
    poisoned_report = get_mutated_models_eval_report(poisonedDataset)
  File "/home/mml/workspace/backdoor_detect/codes/ourMethod/detect_suspicious_classes/analyse.py", line 32, in get_mutated_models_eval_report
    report = em.eval_classification_report()
  File "/home/mml/workspace/backdoor_detect/codes/common/eval_model.py", line 107, in eval_classification_report
    for batch_id, batch in enumerate(testset_loader):
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mml/workspace/backdoor_detect/codes/scripts/dataset_constructor.py", line 180, in __getitem__
    sample,label =self.new_dataset[index]
ValueError: too many values to unpack (expected 2)

Traceback (most recent call last):
  File "/home/mml/workspace/backdoor_detect/codes/ourMethod/detect_suspicious_classes/analyse.py", line 70, in <module>
    poisoned_report = get_mutated_models_eval_report(poisonedDataset)
  File "/home/mml/workspace/backdoor_detect/codes/ourMethod/detect_suspicious_classes/analyse.py", line 32, in get_mutated_models_eval_report
    report = em.eval_classification_report()
  File "/home/mml/workspace/backdoor_detect/codes/common/eval_model.py", line 107, in eval_classification_report
    for batch_id, batch in enumerate(testset_loader):
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mml/workspace/backdoor_detect/codes/scripts/dataset_constructor.py", line 180, in __getitem__
    sample,label =self.new_dataset[index]
ValueError: too many values to unpack (expected 2)

Traceback (most recent call last):
  File "/home/mml/workspace/backdoor_detect/codes/ourMethod/detect_suspicious_classes/analyse.py", line 70, in <module>
    poisoned_report = get_mutated_models_eval_report(poisonedDataset)
  File "/home/mml/workspace/backdoor_detect/codes/ourMethod/detect_suspicious_classes/analyse.py", line 32, in get_mutated_models_eval_report
    report = em.eval_classification_report()
  File "/home/mml/workspace/backdoor_detect/codes/common/eval_model.py", line 107, in eval_classification_report
    for batch_id, batch in enumerate(testset_loader):
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mml/workspace/backdoor_detect/codes/scripts/dataset_constructor.py", line 180, in __getitem__
    sample,label =self.new_dataset[index]
ValueError: too many values to unpack (expected 2)

Traceback (most recent call last):
  File "/home/mml/workspace/backdoor_detect/codes/ourMethod/detect_suspicious_classes/analyse.py", line 70, in <module>
    poisoned_report = get_mutated_models_eval_report(poisonedDataset)
  File "/home/mml/workspace/backdoor_detect/codes/ourMethod/detect_suspicious_classes/analyse.py", line 32, in get_mutated_models_eval_report
    report = em.eval_classification_report()
  File "/home/mml/workspace/backdoor_detect/codes/common/eval_model.py", line 107, in eval_classification_report
    for batch_id, batch in enumerate(testset_loader):
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mml/workspace/backdoor_detect/codes/scripts/dataset_constructor.py", line 180, in __getitem__
    sample,label =self.new_dataset[index]
ValueError: too many values to unpack (expected 2)

Traceback (most recent call last):
  File "/home/mml/workspace/backdoor_detect/codes/ourMethod/detect_suspicious_classes/analyse.py", line 70, in <module>
    poisoned_report = get_mutated_models_eval_report(poisonedDataset)
  File "/home/mml/workspace/backdoor_detect/codes/ourMethod/detect_suspicious_classes/analyse.py", line 32, in get_mutated_models_eval_report
    report = em.eval_classification_report()
  File "/home/mml/workspace/backdoor_detect/codes/common/eval_model.py", line 107, in eval_classification_report
    for batch_id, batch in enumerate(testset_loader):
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mml/workspace/backdoor_detect/codes/scripts/dataset_constructor.py", line 180, in __getitem__
    sample,label =self.new_dataset[index]
ValueError: too many values to unpack (expected 2)

Traceback (most recent call last):
  File "/home/mml/workspace/backdoor_detect/codes/ourMethod/detect_suspicious_classes/analyse.py", line 70, in <module>
    poisoned_report = get_mutated_models_eval_report(poisonedDataset)
  File "/home/mml/workspace/backdoor_detect/codes/ourMethod/detect_suspicious_classes/analyse.py", line 32, in get_mutated_models_eval_report
    report = em.eval_classification_report()
  File "/home/mml/workspace/backdoor_detect/codes/common/eval_model.py", line 107, in eval_classification_report
    for batch_id, batch in enumerate(testset_loader):
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mml/workspace/backdoor_detect/codes/scripts/dataset_constructor.py", line 180, in __getitem__
    sample,label =self.new_dataset[index]
ValueError: too many values to unpack (expected 2)

Traceback (most recent call last):
  File "/home/mml/workspace/backdoor_detect/codes/ourMethod/detect_suspicious_classes/analyse.py", line 70, in <module>
    poisoned_report = get_mutated_models_eval_report(poisonedDataset)
  File "/home/mml/workspace/backdoor_detect/codes/ourMethod/detect_suspicious_classes/analyse.py", line 32, in get_mutated_models_eval_report
    report = em.eval_classification_report()
  File "/home/mml/workspace/backdoor_detect/codes/common/eval_model.py", line 107, in eval_classification_report
    for batch_id, batch in enumerate(testset_loader):
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mml/workspace/backdoor_detect/codes/scripts/dataset_constructor.py", line 180, in __getitem__
    sample,label =self.new_dataset[index]
ValueError: too many values to unpack (expected 2)

Traceback (most recent call last):
  File "/home/mml/workspace/backdoor_detect/codes/ourMethod/detect_suspicious_classes/analyse.py", line 70, in <module>
    poisoned_report = get_mutated_models_eval_report(poisonedDataset)
  File "/home/mml/workspace/backdoor_detect/codes/ourMethod/detect_suspicious_classes/analyse.py", line 32, in get_mutated_models_eval_report
    report = em.eval_classification_report()
  File "/home/mml/workspace/backdoor_detect/codes/common/eval_model.py", line 107, in eval_classification_report
    for batch_id, batch in enumerate(testset_loader):
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mml/workspace/backdoor_detect/codes/scripts/dataset_constructor.py", line 180, in __getitem__
    sample,label =self.new_dataset[index]
ValueError: too many values to unpack (expected 2)

Traceback (most recent call last):
  File "/home/mml/workspace/backdoor_detect/codes/ourMethod/detect_suspicious_classes/analyse.py", line 70, in <module>
    poisoned_report = get_mutated_models_eval_report(poisonedDataset)
  File "/home/mml/workspace/backdoor_detect/codes/ourMethod/detect_suspicious_classes/analyse.py", line 32, in get_mutated_models_eval_report
    report = em.eval_classification_report()
  File "/home/mml/workspace/backdoor_detect/codes/common/eval_model.py", line 107, in eval_classification_report
    for batch_id, batch in enumerate(testset_loader):
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mml/workspace/backdoor_detect/codes/scripts/dataset_constructor.py", line 180, in __getitem__
    sample,label =self.new_dataset[index]
ValueError: too many values to unpack (expected 2)

