CRITICAL:root:Uncaught exception
Traceback (most recent call last):
  File "/home/mml/workspace/backdoor_detect/codes/ASD_baseline.py", line 365, in <module>
    main()
  File "/home/mml/workspace/backdoor_detect/codes/ASD_baseline.py", line 249, in main
    best_ckpt_path, latest_ckpt_path = defence_train(
  File "/home/mml/workspace/backdoor_detect/codes/asd/defence.py", line 335, in defence_train
    record_list = poison_linear_record(model, poisoned_eval_dataset_loader, split_criterion, device, dataset_name=kwargs["dataset_name"], model_name =kwargs["model_name"] )
  File "/home/mml/workspace/backdoor_detect/codes/asd/semi.py", line 101, in poison_linear_record
    output = model(data)
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torchvision/models/resnet.py", line 285, in forward
    return self._forward_impl(x)
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torchvision/models/resnet.py", line 268, in _forward_impl
    x = self.conv1(x)
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 784.00 MiB. GPU 0 has a total capacty of 79.15 GiB of which 714.38 MiB is free. Process 3170600 has 2.60 GiB memory in use. Process 2834422 has 13.56 GiB memory in use. Process 2836860 has 13.56 GiB memory in use. Process 884330 has 9.93 GiB memory in use. Process 1462868 has 37.98 GiB memory in use. Including non-PyTorch memory, this process has 626.00 MiB memory in use. Of the allocated memory 190.75 MiB is allocated by PyTorch, and 21.25 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):
  File "/home/mml/workspace/backdoor_detect/codes/ASD_baseline.py", line 365, in <module>
    main()
  File "/home/mml/workspace/backdoor_detect/codes/ASD_baseline.py", line 249, in main
    best_ckpt_path, latest_ckpt_path = defence_train(
  File "/home/mml/workspace/backdoor_detect/codes/asd/defence.py", line 335, in defence_train
    record_list = poison_linear_record(model, poisoned_eval_dataset_loader, split_criterion, device, dataset_name=kwargs["dataset_name"], model_name =kwargs["model_name"] )
  File "/home/mml/workspace/backdoor_detect/codes/asd/semi.py", line 101, in poison_linear_record
    output = model(data)
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torchvision/models/resnet.py", line 285, in forward
    return self._forward_impl(x)
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torchvision/models/resnet.py", line 268, in _forward_impl
    x = self.conv1(x)
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/mml/anaconda3/envs/backdoor_detect/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 784.00 MiB. GPU 0 has a total capacty of 79.15 GiB of which 714.38 MiB is free. Process 3170600 has 2.60 GiB memory in use. Process 2834422 has 13.56 GiB memory in use. Process 2836860 has 13.56 GiB memory in use. Process 884330 has 9.93 GiB memory in use. Process 1462868 has 37.98 GiB memory in use. Including non-PyTorch memory, this process has 626.00 MiB memory in use. Of the allocated memory 190.75 MiB is allocated by PyTorch, and 21.25 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
